name = "kaihoward"
compatibility_date = "2026-05-15"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "kai-personal-db"
database_id = "7d9dee28-9595-460d-b48c-3d1b5bb0540d"
